import type {
  ProviderBackendConfig,
  ProviderDefinition,
  ProviderType,
  ProviderTypeInfo,
} from './types';

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: '🤖',
    placeholder: 'sk-ant-api03-...',
    model: 'Claude',
    requiresApiKey: true,
    category: 'official',
    envVar: 'ANTHROPIC_API_KEY',
    defaultModelId: 'claude-opus-4-6',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: '💚',
    placeholder: 'sk-proj-...',
    model: 'GPT',
    requiresApiKey: true,
    category: 'official',
    envVar: 'OPENAI_API_KEY',
    defaultModelId: 'gpt-5.2',
    isOAuth: true,
    supportsApiKey: true,
    supportedAuthModes: ['api_key', 'oauth_browser'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.openai.com/v1',
      api: 'openai-responses',
      apiKeyEnv: 'OPENAI_API_KEY',
    },
  },
  {
    id: 'google',
    name: 'Google',
    icon: '🔷',
    placeholder: 'AIza...',
    model: 'Gemini',
    requiresApiKey: true,
    category: 'official',
    envVar: 'GEMINI_API_KEY',
    defaultModelId: 'gemini-3.1-pro-preview',
    isOAuth: true,
    supportsApiKey: true,
    supportedAuthModes: ['api_key', 'oauth_browser'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: '🌐',
    placeholder: 'sk-or-v1-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    showModelId: true,
    modelIdPlaceholder: 'anthropic/claude-opus-4.6',
    defaultModelId: 'anthropic/claude-opus-4.6',
    category: 'compatible',
    envVar: 'OPENROUTER_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://openrouter.ai/api/v1',
      api: 'openai-completions',
      apiKeyEnv: 'OPENROUTER_API_KEY',
      headers: {
        'HTTP-Referer': 'https://claw-x.com',
        'X-Title': 'TnymaAI',
      },
    },
  },
  {
    id: 'ark',
    name: 'ByteDance Ark',
    icon: 'A',
    placeholder: 'your-ark-api-key',
    model: 'Doubao',
    requiresApiKey: true,
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'ep-20260228000000-xxxxx',
    category: 'official',
    envVar: 'ARK_API_KEY',
    codePlanPresetBaseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
    codePlanPresetModelId: 'ark-code-latest',
    codePlanDocsUrl: 'https://www.volcengine.com/docs/82379/1928261?lang=zh',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
      api: 'openai-completions',
      apiKeyEnv: 'ARK_API_KEY',
    },
  },
  {
    id: 'volcengine',
    name: 'Volcano Engine',
    icon: 'V',
    placeholder: 'your-volcengine-api-key',
    model: 'Doubao Code',
    requiresApiKey: true,
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
    defaultModelId: 'ark-code-latest',
    category: 'official',
    envVar: 'VOLCANO_ENGINE_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
      api: 'openai-completions',
      apiKeyEnv: 'VOLCANO_ENGINE_API_KEY',
    },
  },
  {
    id: 'moonshot',
    name: 'Moonshot (CN)',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
    defaultModelId: 'kimi-k2.5',
    category: 'official',
    envVar: 'MOONSHOT_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.moonshot.cn/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MOONSHOT_API_KEY',
      models: [
        {
          id: 'kimi-k2.5',
          name: 'Kimi K2.5',
          reasoning: false,
          input: ['text'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 256000,
          maxTokens: 8192,
        },
      ],
    },
  },
  {
    id: 'moonshot-global',
    name: 'Moonshot',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.moonshot.ai/v1',
    defaultModelId: 'kimi-k2.5',
    category: 'official',
    envVar: 'MOONSHOT_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.moonshot.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MOONSHOT_API_KEY',
    },
  },
  {
    id: 'kimi-code',
    name: 'Kimi Code',
    icon: 'K',
    placeholder: 'sk-...',
    model: 'Kimi Code',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.kimi.com/coding/',
    defaultModelId: 'kimi-code',
    category: 'official',
    envVar: 'KIMI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.kimi.com/coding/',
      api: 'anthropic-messages',
      apiKeyEnv: 'KIMI_API_KEY',
      headers: {
        'User-Agent': 'claude-code/0.1.0',
      },
    },
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow (CN)',
    icon: '🌊',
    placeholder: 'sk-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'deepseek-ai/DeepSeek-V3',
    defaultModelId: 'deepseek-ai/DeepSeek-V3',
    category: 'compatible',
    envVar: 'SILICONFLOW_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.siliconflow.cn/v1',
      api: 'openai-completions',
      apiKeyEnv: 'SILICONFLOW_API_KEY',
    },
  },
  {
    id: 'minimax-portal',
    name: 'MiniMax (Global)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.5',
    apiKeyUrl: 'https://intl.minimaxi.com/',
    category: 'official',
    envVar: 'MINIMAX_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.minimax.io/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'MINIMAX_API_KEY',
    },
  },
  {
    id: 'minimax-portal-cn',
    name: 'MiniMax (CN)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.5',
    apiKeyUrl: 'https://platform.minimaxi.com/',
    category: 'official',
    envVar: 'MINIMAX_CN_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.minimaxi.com/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'MINIMAX_CN_API_KEY',
    },
  },
  {
    id: 'qwen-portal',
    name: 'Qwen',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: false,
    isOAuth: true,
    defaultModelId: 'coder-model',
    category: 'official',
    envVar: 'QWEN_API_KEY',
    supportedAuthModes: ['oauth_device'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://portal.qwen.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'QWEN_API_KEY',
    },
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    icon: '𝕏',
    placeholder: 'xai-...',
    model: 'Grok',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.x.ai/v1',
    defaultModelId: 'grok-4',
    category: 'official',
    envVar: 'XAI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.x.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'XAI_API_KEY',
    },
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    icon: 'M',
    placeholder: 'mistral-...',
    model: 'Mistral',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    defaultModelId: 'mistral-large-latest',
    category: 'official',
    envVar: 'MISTRAL_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.mistral.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MISTRAL_API_KEY',
    },
  },
  {
    id: 'byteplus',
    name: 'BytePlus',
    icon: 'B',
    placeholder: 'byteplus-...',
    model: 'BytePlus Code',
    requiresApiKey: true,
    defaultBaseUrl: 'https://ark.ap-southeast.bytepluses.com/api/coding/v3',
    defaultModelId: 'ark-code-latest',
    category: 'official',
    envVar: 'BYTEPLUS_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://ark.ap-southeast.bytepluses.com/api/coding/v3',
      api: 'openai-completions',
      apiKeyEnv: 'BYTEPLUS_API_KEY',
    },
  },
  {
    id: 'kilocode',
    name: 'Kilo Gateway',
    icon: 'K',
    placeholder: 'sk-...',
    model: 'Gateway',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.kilo.ai/api/gateway/',
    defaultModelId: 'kilo/auto',
    category: 'compatible',
    envVar: 'KILOCODE_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.kilo.ai/api/gateway/',
      api: 'openai-completions',
      apiKeyEnv: 'KILOCODE_API_KEY',
    },
  },
  {
    id: 'zai',
    name: 'Z.AI',
    icon: 'Z',
    placeholder: 'zai-...',
    model: 'GLM',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.z.ai/api/paas/v4',
    defaultModelId: 'glm-5',
    showBaseUrl: true,
    category: 'official',
    envVar: 'ZAI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.z.ai/api/paas/v4',
      api: 'openai-completions',
      apiKeyEnv: 'ZAI_API_KEY',
    },
  },
  {
    id: 'qianfan',
    name: 'Qianfan',
    icon: '千',
    placeholder: 'qf-...',
    model: 'Qianfan',
    requiresApiKey: true,
    defaultBaseUrl: 'https://qianfan.baidubce.com/v2',
    defaultModelId: 'deepseek-v3.2',
    category: 'official',
    envVar: 'QIANFAN_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://qianfan.baidubce.com/v2',
      api: 'openai-completions',
      apiKeyEnv: 'QIANFAN_API_KEY',
    },
  },
  {
    id: 'modelstudio',
    name: 'Alibaba Cloud Model Studio',
    icon: 'Q',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: true,
    defaultBaseUrl: 'https://coding-intl.dashscope.aliyuncs.com/v1',
    defaultModelId: 'qwen3.5-plus',
    showBaseUrl: true,
    category: 'official',
    envVar: 'MODELSTUDIO_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://coding-intl.dashscope.aliyuncs.com/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MODELSTUDIO_API_KEY',
    },
  },
  {
    id: 'vercel-ai-gateway',
    name: 'Vercel AI Gateway',
    icon: 'V',
    placeholder: 'vgw-...',
    model: 'Gateway',
    requiresApiKey: true,
    defaultBaseUrl: 'https://ai-gateway.vercel.sh',
    defaultModelId: 'anthropic/claude-opus-4.6',
    category: 'compatible',
    envVar: 'AI_GATEWAY_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://ai-gateway.vercel.sh',
      api: 'anthropic-messages',
      apiKeyEnv: 'AI_GATEWAY_API_KEY',
    },
  },
  {
    id: 'xiaomi',
    name: 'Xiaomi',
    icon: 'X',
    placeholder: 'sk-...',
    model: 'MiMo',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.xiaomimimo.com/v1',
    defaultModelId: 'mimo-v2-flash',
    category: 'official',
    envVar: 'XIAOMI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.xiaomimimo.com/v1',
      api: 'openai-completions',
      apiKeyEnv: 'XIAOMI_API_KEY',
    },
  },
  {
    id: 'synthetic',
    name: 'Synthetic',
    icon: 'S',
    placeholder: 'synthetic-...',
    model: 'Anthropic-compatible',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.synthetic.new/anthropic',
    defaultModelId: 'hf:MiniMaxAI/MiniMax-M2.5',
    category: 'compatible',
    envVar: 'SYNTHETIC_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.synthetic.new/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'SYNTHETIC_API_KEY',
    },
  },
  {
    id: 'together',
    name: 'Together AI',
    icon: 'T',
    placeholder: 'together-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.together.xyz/v1',
    defaultModelId: 'moonshotai/Kimi-K2.5',
    category: 'compatible',
    envVar: 'TOGETHER_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.together.xyz/v1',
      api: 'openai-completions',
      apiKeyEnv: 'TOGETHER_API_KEY',
    },
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    icon: '🤗',
    placeholder: 'hf_...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://router.huggingface.co/v1',
    defaultModelId: 'deepseek-ai/DeepSeek-R1',
    category: 'compatible',
    envVar: 'HUGGINGFACE_HUB_TOKEN',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://router.huggingface.co/v1',
      api: 'openai-completions',
      apiKeyEnv: 'HUGGINGFACE_HUB_TOKEN',
    },
  },
  {
    id: 'venice',
    name: 'Venice AI',
    icon: 'V',
    placeholder: 'venice-...',
    model: 'Venice',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.venice.ai/api/v1',
    defaultModelId: 'kimi-k2-5',
    category: 'official',
    envVar: 'VENICE_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.venice.ai/api/v1',
      api: 'openai-completions',
      apiKeyEnv: 'VENICE_API_KEY',
    },
  },
  {
    id: 'litellm',
    name: 'LiteLLM',
    icon: 'L',
    placeholder: 'sk-...',
    model: 'Gateway',
    requiresApiKey: true,
    defaultBaseUrl: 'http://localhost:4000',
    defaultModelId: 'claude-opus-4-6',
    showBaseUrl: true,
    category: 'compatible',
    envVar: 'LITELLM_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'http://localhost:4000',
      api: 'openai-completions',
      apiKeyEnv: 'LITELLM_API_KEY',
    },
  },
  {
    id: 'sglang',
    name: 'SGLang',
    icon: 'S',
    placeholder: 'Not required',
    model: 'Self-hosted',
    requiresApiKey: false,
    defaultBaseUrl: 'http://127.0.0.1:30000/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'Qwen/Qwen3-8B',
    category: 'local',
    envVar: 'SGLANG_API_KEY',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'http://127.0.0.1:30000/v1',
      api: 'openai-completions',
      apiKeyEnv: 'SGLANG_API_KEY',
    },
  },
  {
    id: 'vllm',
    name: 'vLLM',
    icon: 'v',
    placeholder: 'Not required',
    model: 'Self-hosted',
    requiresApiKey: false,
    defaultBaseUrl: 'http://127.0.0.1:8000/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'meta-llama/Meta-Llama-3-8B-Instruct',
    category: 'local',
    envVar: 'VLLM_API_KEY',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'http://127.0.0.1:8000/v1',
      api: 'openai-completions',
      apiKeyEnv: 'VLLM_API_KEY',
    },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    icon: '🦙',
    placeholder: 'Not required',
    requiresApiKey: false,
    defaultBaseUrl: 'http://localhost:11434/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'qwen3:latest',
    category: 'local',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
  },
  {
    id: 'custom',
    name: 'Custom',
    icon: '⚙️',
    placeholder: 'API key...',
    requiresApiKey: true,
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'your-provider/model-id',
    category: 'custom',
    envVar: 'CUSTOM_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
];

const PROVIDER_DEFINITION_MAP = new Map(
  PROVIDER_DEFINITIONS.map((definition) => [definition.id, definition]),
);

export function getProviderDefinition(
  type: ProviderType | string,
): ProviderDefinition | undefined {
  return PROVIDER_DEFINITION_MAP.get(type as ProviderType);
}

export function getProviderTypeInfo(
  type: ProviderType,
): ProviderTypeInfo | undefined {
  return getProviderDefinition(type);
}

export function getProviderEnvVar(type: string): string | undefined {
  return getProviderDefinition(type)?.envVar;
}

export function getProviderDefaultModel(type: string): string | undefined {
  return getProviderDefinition(type)?.defaultModelId;
}

export function getProviderBackendConfig(
  type: string,
): ProviderBackendConfig | undefined {
  return getProviderDefinition(type)?.providerConfig;
}

export function getProviderUiInfoList(): ProviderTypeInfo[] {
  return PROVIDER_DEFINITIONS;
}

export function getKeyableProviderTypes(): string[] {
  return PROVIDER_DEFINITIONS.filter((definition) => definition.envVar).map(
    (definition) => definition.id,
  );
}
